#!/usr/bin/env bash
# coturn setup script for Oracle Cloud Always Free VPS (or any Debian/Ubuntu VPS).
#
# This script:
#   1. Installs coturn
#   2. Generates a config file with sensible defaults
#   3. Sets up a strong shared secret (HMAC-style credentials)
#   4. Opens the firewall (iptables + Oracle security list reminder)
#   5. Optionally provisions a TLS cert via Let's Encrypt (if you have a domain)
#   6. Starts coturn and enables it on boot
#
# After it finishes, copy the printed TURN_URLS / TURN_USERNAME /
# TURN_CREDENTIAL values into your Vercel / Cloudflare env vars.
#
# Run on the VPS as root (or with sudo):
#   bash coturn-setup.sh [--domain turn.yourdomain.com] [--user proxyuser]
#
# If you don't have a domain, omit --domain — coturn will run without TLS
# on port 3478 only. Most browsers accept this for game streaming.
# (Xbox Cloud Gaming uses TURN over UDP on 3478, so TLS is not required.)

set -euo pipefail

# ── Defaults ────────────────────────────────────────────────────────────────
DOMAIN=""
USERNAME="proxyuser"
LISTEN_PORT=3478
TLS_PORT=5349
RELAY_MIN=49152
RELAY_MAX=65535
REALM="oracle-cloud"

# ── Parse args ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case $1 in
    --domain)
      DOMAIN="$2"; shift 2 ;;
    --user)
      USERNAME="$2"; shift 2 ;;
    --realm)
      REALM="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: bash coturn-setup.sh [--domain turn.yourdomain.com] [--user proxyuser] [--realm oracle-cloud]"
      exit 0 ;;
    *)
      echo "Unknown argument: $1"; exit 1 ;;
  esac
done

# ── Generate a strong password ──────────────────────────────────────────────
PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
echo "→ Generated password (save this): $PASSWORD"

# ── Install coturn ─────────────────────────────────────────────────────────
echo "→ Installing coturn..."
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq coturn certbot

# Enable the service
echo "TURNSERVER_ENABLED=1" > /etc/default/coturn

# ── Build the config ────────────────────────────────────────────────────────
echo "→ Writing /etc/turnserver.conf..."

if [[ -n "$DOMAIN" ]]; then
  TLS_BLOCK="tls-listening-port=${TLS_PORT}
cert=/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
pkey=/etc/letsencrypt/live/${DOMAIN}/privkey.pem"
else
  TLS_BLOCK="# TLS disabled — no domain specified. Most game streaming works without TLS."
fi

cat > /etc/turnserver.conf << EOF
# coturn configuration — generated by coturn-setup.sh
# Generated: $(date -u)

# Listening ports
listening-port=${LISTEN_PORT}
${TLS_BLOCK}

# Authentication
realm=${REALM}
server-name=${REALM}
fingerprint
lt-cred-mech
user=${USERNAME}:${PASSWORD}

# Quotas & limits (tune for your usage)
total-quota=200
stale-nonce=600
# bps-capacity=0 means unlimited bandwidth
bps-capacity=0

# Relay port range — must match firewall rules
min-port=${RELAY_MIN}
max-port=${RELAY_MAX}

# Security
no-multicast-peers
no-cli
# Allow TCP relay (some networks block UDP; TCP fallback is useful)
# Comment out the next line to allow TCP relay
# no-tcp-relay
no-sslv2
no-sslv3
no-tlsv1
no-tlsv1_1
cipher-list=HIGH

# Logging (set to "debug" for verbose logs, "warning" for quiet)
log-file=/var/log/turnserver.log
simple-log
EOF

# Make sure log file is writable
touch /var/log/turnserver.log
chown turn:turn /var/log/turnserver.log 2>/dev/null || true

# ── Firewall: iptables ──────────────────────────────────────────────────────
echo "→ Opening iptables rules..."

# TCP listening port
iptables -I INPUT -p tcp --dport ${LISTEN_PORT} -j ACCEPT 2>/dev/null || true
# UDP listening port
iptables -I INPUT -p udp --dport ${LISTEN_PORT} -j ACCEPT 2>/dev/null || true
# TLS port (if using TLS)
if [[ -n "$DOMAIN" ]]; then
  iptables -I INPUT -p tcp --dport ${TLS_PORT} -j ACCEPT 2>/dev/null || true
fi
# UDP relay port range
iptables -I INPUT -p udp --dport ${RELAY_MIN}:${RELAY_MAX} -j ACCEPT 2>/dev/null || true

# Save iptables rules so they survive reboot
if command -v netfilter-persistent >/dev/null 2>&1; then
  netfilter-persistent save
else
  echo "→ Installing iptables-persistent to save rules across reboots..."
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq iptables-persistent
  netfilter-persistent save
fi

# ── Optional: Let's Encrypt TLS cert ────────────────────────────────────────
if [[ -n "$DOMAIN" ]]; then
  echo "→ Requesting TLS certificate for $DOMAIN via Let's Encrypt..."
  # Stop coturn so certbot can use port 80
  systemctl stop coturn 2>/dev/null || true
  certbot certonly --standalone -n --agree-tos --register-unsafely-without-email -d "$DOMAIN"
  # Make sure coturn can read the cert files
  chmod -R 755 /etc/letsencrypt/live/
  chmod -R 755 /etc/letsencrypt/archive/
fi

# ── Start coturn ────────────────────────────────────────────────────────────
echo "→ Starting coturn..."
systemctl enable coturn
systemctl restart coturn

sleep 2

if systemctl is-active --quiet coturn; then
  echo "✓ coturn is running"
else
  echo "✗ coturn failed to start. Check logs:"
  echo "  sudo journalctl -u coturn -n 50 --no-pager"
  exit 1
fi

# ── Print the env vars to set on Vercel / Cloudflare ────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "✓ coturn is live. Set these env vars on your Vercel / Cloudflare deployment:"
echo "═══════════════════════════════════════════════════════════════════════════"
if [[ -n "$DOMAIN" ]]; then
  echo "TURN_URLS=turn:${DOMAIN}:${LISTEN_PORT},turns:${DOMAIN}:${TLS_PORT}"
else
  # Fall back to the server's public IP
  PUBLIC_IP=$(curl -s https://api.ipify.org || curl -s https://ifconfig.me)
  echo "TURN_URLS=turn:${PUBLIC_IP}:${LISTEN_PORT}"
fi
echo "TURN_USERNAME=${USERNAME}"
echo "TURN_CREDENTIAL=${PASSWORD}"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "→ Also open these ports in the Oracle Cloud security list (VCN → Security Lists):"
echo "  • TCP ${LISTEN_PORT}  (coturn listener)"
if [[ -n "$DOMAIN" ]]; then
  echo "  • TCP ${TLS_PORT}    (TURNS — TURN over TLS)"
fi
echo "  • UDP ${LISTEN_PORT}  (coturn listener)"
echo "  • UDP ${RELAY_MIN}-${RELAY_MAX}  (relay ports for actual video traffic)"
echo ""
echo "→ Test that your TURN server is reachable:"
if [[ -n "$DOMAIN" ]]; then
  echo "  https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/"
  echo "  Add a TURN server: turn:${USERNAME}@${DOMAIN}:${LISTEN_PORT} with credential"
else
  echo "  curl -v stun:${PUBLIC_IP}:${LISTEN_PORT}  (won't return anything but should connect)"
fi
